packages:
  - packages/*
  - ndk-core
  - ndk-test
  - ndk-test-utils
  - ndk-cache-dexie
  - ndk-svelte
  - ndk-hooks
  - ndk-svelte-components
  - ndk-wallet
onlyBuiltDependencies:
  - bufferutil
  - es5-ext
  - esbuild
  - msw
  - svelte-preprocess
  - utf-8-validate
